###
@HostAddress = https://localhost:7037
GET {{SirPixAlot.WebAPI_HostAddress}}/weatherforecast
Accept: application/json

###
GET {{HostAddress}}/api/canvas?x=0&y=0
Accept: application/json

###
PUT {{HostAddress}}/api/canvas
Accept: application/json
Content-Type: application/json

{
  "x":0,
  "y":0,
  "color": "#AA33FF"
}