###
#@HostAddress = http://localhost:7037
@HostAddress = http://13.251.68.209:80
GET {{HostAddress}}/weatherforecast
Accept: application/json

###
GET {{HostAddress}}/api/canvas?x=0&y=0
Accept: application/json

###
PUT {{HostAddress}}/api/canvas
Accept: application/json
Content-Type: application/json

{
  "x":0,
  "y":0,
  "color": "#AA33FF"
}