###
@HostAddress = https://localhost:7037
#@HostAddress = http://172.104.37.82
GET {{HostAddress}}/weatherforecast
Accept: application/json

###
GET {{HostAddress}}/api/canvas/pixel?x=0&y=0
Accept: application/json

###
GET {{HostAddress}}/api/canvas/rectangle?topLeftX=0&topLeftY=0&bottomRightX=10&bottomRightY=-10
Accept: application/json
Origin: localhost:90

###
PUT {{HostAddress}}/api/canvas
Accept: application/json
Content-Type: application/json

{
  "x":0,
  "y":0,
  "color": "#AA00FF"
}