# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Aspire

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: |
        dotnet workload update 
        dotnet workload install aspire
        dotnet workload list
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install Aspirate
      run: dotnet tool install -g aspirate --prerelease
    - name: Generate k8s yaml
      working-directory: ./SirPixAlot.Aspire.AppHost/
      run: aspirate generate --non-interactive --secret-password ${{ secrets.ASPIRATE_PASSWORD }} --image-pull-policy Always --output-path "./deployment/aspirate-output/"
    - name: Copy cluster 
      working-directory: ./SirPixAlot.Aspire.AppHost/
      run: cp -r ./cluster-config/* ./deployment
    - name: List docker images
      run: docker images
    - uses: actions/upload-artifact@v4
      with:
        name: aspirate-output
        path: ./SirPixAlot.Aspire.AppHost/deployment/

  deploy:
    needs: build
    defaults:
      run:
        working-directory: ./SirPixAlot.Aspire.AppHost
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4.1.4
      with: 
        path: ./SirPixAlot.Aspire.AppHost/deployment/
    - name: Create WebAPi Secrets
      run: |
        echo "${{ secrets.SIRPIXALOTWEBAPI_SECRETS }}" >> "./deployment/aspirate-output/aspirate-output/SirPixAlotWebAPI/.sirpixalotwebapi.secrets"
        cat "./deployment/aspirate-output/aspirate-output/SirPixAlotWebAPI/.sirpixalotwebapi.secrets"
    - name: Check folder structure
      run: |
        sudo apt install tree
        tree .
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -k SirPixAlot.Aspire.AppHost/deployment/aspirate-output/aspirate-output/

