# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Aspire

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: |
        dotnet workload update 
        dotnet workload install aspire
        dotnet workload list
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Aspirate
      run: dotnet tool install -g aspirate --prerelease
    - name: Generate k8s yaml
      working-directory: ./SirPixAlot.Aspire.AppHost/
      run: aspirate generate --non-interactive --disable-secrets --include-dashboard --image-pull-policy IfNotPresent 
    - name: List docker images
      run: docker images
    - uses: actions/upload-artifact@v4
      with:
        name: aspirate-output
        path: ./SirPixAlot.Aspire.AppHost/aspirate-output/
