# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Fly.IO

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Aspire
      run: |
        dotnet workload update 
        dotnet workload install aspire
        dotnet workload list
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install Aspirate
      run: dotnet tool install -g aspirate --prerelease
    - name: Build Docker Images using aspirate
      working-directory: ./SirPixAlot.Aspire.AppHost/
      run: aspirate build --non-interactive --disable-secrets
    - name: List docker images
      run: docker images
      

  deploy-sirpixalotwebapi:
    needs: build
    defaults:
      run:
        working-directory: ./Deployments/fly-io/sirpixalotwebapi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

